### ISSUE TITLE
Wlan Problem

### ISSUE THREAD

**Issue by xiubu-mk** [KlausLi/EspSoyosourceController#1]
Hallo KlausLi,

danke für das tolle Projekt !!
Ich bekomme es nicht mit meinem Wlan verbunden.
Es meldet sich beim Router zwar an, bekommt auch eine IP Adresse ist aber nicht wirklich erreichbar.
Und macht wieder einen AP auf.

Gruß xiubu-mk

**Comment by damark234** [comment]
Hallo,
ja selbes Problem hier.
Bekomme SSID und SSID1 angezeigt aber egal was ich fülle bekomme ich meist keine Verbindung und wenn dann eine nicht erreichbare. 

Gruß

**Comment by KlausLi** [comment]
> Hallo KlausLi,
> 
> danke für das tolle Projekt !! Ich bekomme es nicht mit meinem Wlan verbunden. Es meldet sich beim Router zwar an, bekommt auch eine IP Adresse ist aber nicht wirklich erreichbar. Und macht wieder einen AP auf.
> 
> Gruß xiubu-mk

Hallo 
Danke für deine Rückmeldung.
Ich werd dann mal einen frischen ESP nehmen und schauen worans liegt .
Welchen ESP verwendest du ?
gruß Klaus

**Comment by KlausLi** [comment]
> Hallo, ja selbes Problem hier. Bekomme SSID und SSID1 angezeigt aber egal was ich fülle bekomme ich meist keine Verbindung und wenn dann eine nicht erreichbare.
> 
> Gruß

Hallo 
Danke für deine Rückmeldung.
Ich werd dann mal einen frischen ESP nehmen und schauen worans liegt .
Welchen ESP verwendest du ?
gruß Klaus

**Comment by damark234** [comment]
Hallo,

ich habe aktuell zu Testzwecken und weil ich ein Newbe bin ein Nodemcu V3 mit ESP12-F genommen.
Welche Hardware würdest du empfehlen?

Grüße

**Comment by KlausLi** [comment]
Esp12 ist ok , der hat ja 4mbyte Flash
Empfehlen tu i nix , ich nehm selber her was rumliegt oder bau's von anderen Projekten wieder aus ;-) 

aber so dev Boards wie Nodemcu oder wemu ... habe ich gar nicht 
hab mir vor Jahren mal n Schwung esp12's -F geordert, die sind etzad alle :-)
Macht aber Sinn fürs Probieren sich so Dev Boards zuzulegen :-)

**Comment by damark234** [comment]
Wifi zum Router geht, habe ich gerade per Skript verbunden.  Also scheint es daran schon mal nicht zu hängen. 

![WIFI SSIDs](https://user-images.githubusercontent.com/91720646/135590330-720148c0-11fd-4494-8cf5-39b07964c0ba.JPG)

So sieht die Maske aus bei mir. Hab eben auch ein neues Board genommen aber gleiches Verhalten.

**Comment by KlausLi** [comment]
> Wifi zum Router geht, habe ich gerade per Skript verbunden. Also scheint es daran schon mal nicht zu hängen.
> 
> ![WIFI SSIDs](https://user-images.githubusercontent.com/91720646/135590330-720148c0-11fd-4494-8cf5-39b07964c0ba.JPG)
> 
> So sieht die Maske aus bei mir. Hab eben auch ein neues Board genommen aber gleiches Verhalten.

kanns grad selber nachvollziehen :-(

bei mir ignoriert er die erfolgreiche speicherung und geht wieder in AP Mode, als ob er die config ´mit den wlans nicht anlegt 
ich switche die firmware's zurück und sehe nach was da passiert ist 
daß is nix grosses , es heisst nur wieder mal configportal *würg
... irgenwann nehm ich mir ein Herz

**Comment by xiubu-mk** [comment]
> > Hallo KlausLi,
> > danke für das tolle Projekt !! Ich bekomme es nicht mit meinem Wlan verbunden. Es meldet sich beim Router zwar an, bekommt auch eine IP Adresse ist aber nicht wirklich erreichbar. Und macht wieder einen AP auf.
> > Gruß xiubu-mk
> 
> Hallo Danke für deine Rückmeldung. Ich werd dann mal einen frischen ESP nehmen und schauen worans liegt . Welchen ESP verwendest du ? gruß Klaus

Hallo Klaus,

ich verwende eine D1 mini mit 4MB  (ESP8266-12). Um einen Defekt des ESPs auszuschließen habe ich auch Tasmota geflasht. Dort klappt das WLAN

Gruß xiubu-mk

**Comment by KlausLi** [comment]
> > > Hallo KlausLi,
> > > danke für das tolle Projekt !! Ich bekomme es nicht mit meinem Wlan verbunden. Es meldet sich beim Router zwar an, bekommt auch eine IP Adresse ist aber nicht wirklich erreichbar. Und macht wieder einen AP auf.
> > > Gruß xiubu-mk
> > 
> > 
> > Hallo Danke für deine Rückmeldung. Ich werd dann mal einen frischen ESP nehmen und schauen worans liegt . Welchen ESP verwendest du ? gruß Klaus
> 
> Hallo Klaus,
> 
> ich verwende eine D1 mini mit 4MB (ESP8266-12). Um einen Defekt des ESPs auszuschließen habe ich auch Tasmota geflasht. Dort klappt das WLAN
> 
> Gruß xiubu-mk

bi version 1.0.0.5 klappz kann noch keinen fehler finden 
ich suche weiter ...

**Comment by KlausLi** [comment]
Version 1.0.1.3 ist online und sollte das beheben , ist leider bei mir nicht aufgefallen hatte Configportal nicht zum testen auf dem Schirm.

**Comment by KlausLi** [comment]
> Hallo KlausLi,
> 
> danke für das tolle Projekt !! Ich bekomme es nicht mit meinem Wlan verbunden. Es meldet sich beim Router zwar an, bekommt auch eine IP Adresse ist aber nicht wirklich erreichbar. Und macht wieder einen AP auf.
> 
> Gruß xiubu-mk

Sorry  war zu voreilig , funktionierts bei dir nun mit der neuen Funktion ?

**Comment by damark234** [comment]
WIFI funktioniert nun! Danke

**Comment by KlausLi** [comment]
super :-) 
welche soyosource  version nutz du ?
 wie schauts bei xiubu aus ?

**Comment by damark234** [comment]
Muss ich noch schauen, kam heute an und der Akku ist noch nicht Ready.

MQTT Abfrage der Hausautomatik ist der nächste Punkt.

Grüße

**Comment by xiubu-mk** [comment]
> 
> 
> super :-) welche soyosource version nutz du ? wie schauts bei xiubu aus ?

Wifi läuft bei mir nun auch, vielen Dank Klaus für den schnellen Support ;-)
