### ISSUE TITLE
Probleme mit der Inbetriebnahme ?

### ISSUE THREAD

**Issue by KlausLi** [KlausLi/EspSoyosourceController#3]
Falls Ihr Probleme habt , immer rein damit .

**Comment by damark234** [comment]
Hi, mal wieder das leidige Wifi Thema. Nun scheint er die Maske zur Eingabe des PW und der MQTT Daten nicht mehr anzeigen zu wollen.
Version 1.0.1.3

![image](https://user-images.githubusercontent.com/91720646/135621491-4a6324b1-d356-4942-b385-15f47e61bb5c.png)


Grüße

**Comment by KlausLi** [comment]
sorry hab ne neue version in der das timing noch in wenig besser wird hochgeladen

warscheinl. wärs beim 2 ten oder xten versuch bei dir gegangen aber versuch diese version mal ohnendie Entfernung zum ESp zu ändern zu konfigurieren .
Ansonsten immer so Nahe im Ap Modus wies geht zum esp hingehen mit dem Client

**Comment by KlausLi** [comment]
> Hi, mal wieder das leidige Wifi Thema. Nun scheint er die Maske zur Eingabe des PW und der MQTT Daten nicht mehr anzeigen zu wollen. Version 1.0.1.3
> 
> ![image](https://user-images.githubusercontent.com/91720646/135621491-4a6324b1-d356-4942-b385-15f47e61bb5c.png)
> 
> Grüße

sorry hab ne neue version in der das timing noch in wenig besser wird hochgeladen

warscheinl. wärs beim 2 ten oder xten versuch bei dir gegangen aber versuch diese version mal ohne die Entfernung zum ESp zu ändern und das wlan zu konfigurieren .
Ansonsten immer so Nahe im Ap Modus wies geht zum esp hingehen mit dem Client
